### ISSUE TITLE
Fix mobile background image

### ISSUE THREAD

**Issue by yesseruser** [Yesser-Studios/Yesser-Notes.Pages#11]
This is how it looks on mobile: ![Screenshot_20230427-113626.png](https://user-images.githubusercontent.com/67008763/234823136-2546ee8d-81c1-4c7c-bb26-866b8a6426e5.png)
Fix this, please

**Comment by naim16031988** [comment]
Hi, I did not get your idea very well. do you want to put the screen shot as a background image?
there is what i am proposing : i attached a screen shot of the ap
<img width="275" alt="Screenshot 2023-04-29 013400" src="https://user-images.githubusercontent.com/125624860/235285547-4077f921-26b6-47ce-b726-e57f094f9f66.png">
p on mobile

**Comment by yesseruser** [comment]
This looks okay I think, but make the background a bit darker to match the background of the app.
