### ISSUE TITLE
Make the index.html page's Header without padding/margin on sides

### ISSUE THREAD

**Issue by yesseruser** [Yesser-Studios/Yesser-Notes.Pages#12]
- Make the Header fill the entire width of the screen, or
- Change the Header to a div and make it fill the entire width of the screen.

**Comment by yesseruser** [comment]
This issue seems to be harder than I throught.

**Comment by anand-tiwary0** [comment]
can you elaborate this issue

**Comment by yesseruser** [comment]
Changed the issue description.
